### ISSUE TITLE
Redundant call

### ISSUE THREAD

**Issue by AssafMiron** [infamousjoeg/workshop-orchestration#1]
https://github.com/infamousjoeg/workshop-orchestration/blob/d3dcc8ba1444591fddfb72ae80e6c8d7b77ac097/deploy.ps1#L74

Once you add an LDAP user to a safe as a member, this user is created

So you don't really need this API call to login with the user, it is enough to leave the section where you add the user as member to the safe

**Comment by infamousjoeg** [comment]
Ok, I wasn't sure if I needed to assign the EPVUser license to the AD User (through an initial login) before I could actually "SearchIn: domain.com" to find the user.
